In [1]:
import pandas as pd
import numpy as np

In [2]:
#los dataframes se pueden crear a partir de  diccionarios

In [6]:
df1 = pd.DataFrame({'key':list ('bbacaab'),\
                    'data1':range(7)})

In [7]:
df2 = pd.DataFrame({'key':list ('abd'),\
                    'data2':range(3)})

df1 

In [8]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [9]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [10]:
pd.merge(df1,df2)#pone primero los comunes y luego los disjuntos

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [13]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [20]:
df4 = pd.DataFrame({'lkey':list ('bbacaab'),\
                    'data1':range(7)})
df5 = pd.DataFrame({'rkey':list ('abd'),\
                    'data2':range(3)})

In [21]:
df4

data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [22]:
df5

data2 rkey
0      0    a
1      1    b
2      2    d

In [25]:
#pd.merge(df4,df5) #no funciona porque debe tener columnas comunes

In [24]:
pd.merge(df4,df5,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [26]:
pd.merge(df4,df5,left_on='lkey',right_on='rkey',how='inner')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [27]:
pd.merge(df4,df5,left_on='lkey',right_on='rkey',how='left')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      2    a      0    a
3      3    c    NaN  NaN
4      4    a      0    a
5      5    a      0    a
6      6    b      1    b

In [28]:
pd.merge(df4,df5,left_on='lkey',right_on='rkey',how='outer')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a
6      3    c    NaN  NaN
7    NaN  NaN      2    d

In [33]:
left = pd.DataFrame({'key1':list('aab'),
                     'key2':list('bnm'),
                     'key3':range(3)                    
                    })

right = pd.DataFrame({'key1':list('aabb'),
                      'key2':list('bbbm'),
                      'rval':[6,7,8,9]              
                    })

In [34]:
right

key1 key2  rval
0    a    b     6
1    a    b     7
2    b    b     8
3    b    m     9

In [35]:
left

key1 key2  key3
0    a    b     0
1    a    n     1
2    b    m     2

In [36]:
pd.merge(left,right,on=['key1','key2'])

key1 key2  key3  rval
0    a    b     0     6
1    a    b     0     7
2    b    m     2     9

In [39]:
pd.merge(left,right,on=['key1']) #mete un sufijo para no pisar valores

key1 key2_x  key3 key2_y  rval
0    a      b     0      b     6
1    a      b     0      b     7
2    a      n     1      b     6
3    a      n     1      b     7
4    b      m     2      b     8
5    b      m     2      m     9

In [40]:
pd.merge(left,right,on=['key1'],suffixes=['_left','_right'])

key1 key2_left  key3 key2_right  rval
0    a         b     0          b     6
1    a         b     0          b     7
2    a         n     1          b     6
3    a         n     1          b     7
4    b         m     2          b     8
5    b         m     2          m     9

In [41]:
## Merging on index

In [49]:
left1=left

In [50]:
right1 = pd.DataFrame({'vals':[5,8]},index=['a','b'])

In [51]:
right1

vals
a     5
b     8

In [52]:
pd.merge(left1,right1,left_on='key1',right_index=True)

key1 key2  key3  vals
0    a    b     0     5
1    a    n     1     5
2    b    m     2     8

In [55]:
#ejemplo de indes jerarquico

In [57]:
right_h = pd.DataFrame(np.arange(12).reshape(6,2))

In [58]:
right_h

0   1
0   0   1
1   2   3
2   4   5
3   6   7
4   8   9
5  10  11

In [61]:
right_h2 = pd.DataFrame(np.arange(12).reshape(6,2),index = [list('aabbxx'),list('bbnnnn')])

In [62]:
right_h2

0   1
a b   0   1
  b   2   3
b n   4   5
  n   6   7
x n   8   9
  n  10  11

In [65]:
pd.merge(left,right_h2,left_on=['key1','key2'],right_index=True)

key1 key2  key3  0  1
0    a    b     0  0  1
0    a    b     0  2  3

In [66]:
pd.merge(left,right_h2,left_on=['key1','key2'],right_index=True,how='outer')

key1 key2  key3   0   1
0    a    b     0   0   1
0    a    b     0   2   3
1    a    n     1 NaN NaN
2    b    m     2 NaN NaN
2    b    n   NaN   4   5
2    b    n   NaN   6   7
2    x    n   NaN   8   9
2    x    n   NaN  10  11

In [67]:
pd.merge(left,right_h2,left_on=['key1','key2'],right_index=True,how='left')

key1 key2  key3   0   1
0    a    b     0   0   1
0    a    b     0   2   3
1    a    n     1 NaN NaN
2    b    m     2 NaN NaN

In [68]:
## Concatenating

In [69]:
arr = np.arange(12).reshape(3,4) #arrays de numpy

In [70]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
np.concatenate ( [arr,arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
np.concatenate ( [arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [76]:
s1 = pd.Series([0,1],index = ['a','b'])

In [77]:
s2 = pd.Series([2,3,4],index = list('cde'))

In [78]:
s3 = pd.Series([5,6],index = ['f','g'])

In [79]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [82]:
x = pd.concat([s1,s2,s3],axis=1)

In [83]:
x

0   1   2
a   0 NaN NaN
b   1 NaN NaN
c NaN   2 NaN
d NaN   3 NaN
e NaN   4 NaN
f NaN NaN   5
g NaN NaN   6

In [84]:
type('x')

str

x2 = pd.concat([s1,s2,s3],axis=1,keys=list('ijk'))

In [88]:
x2 = pd.concat([s1,s2,s3],axis=1,keys=list('ijk'))

In [89]:
x2

i   j   k
a   0 NaN NaN
b   1 NaN NaN
c NaN   2 NaN
d NaN   3 NaN
e NaN   4 NaN
f NaN NaN   5
g NaN NaN   6

In [92]:
df6 = pd.concat([s1,s2,s3],axis=1,keys=list('ijk')).fillna(42)

In [93]:
df7 = pd.DataFrame(np.random.randn(2,2),columns = ['i','j'])

In [94]:
df7

i         j
0  0.011167  1.037082
1 -1.159355 -2.087657

In [95]:
pd.concat([df6,df7])

i          j   k
a   0.000000  42.000000  42
b   1.000000  42.000000  42
c  42.000000   2.000000  42
d  42.000000   3.000000  42
e  42.000000   4.000000  42
f  42.000000  42.000000   5
g  42.000000  42.000000   6
0   0.011167   1.037082 NaN
1  -1.159355  -2.087657 NaN

In [97]:
df6.append(df7) #lo mismo que el anterioe pero consume menos memoria

i          j   k
a   0.000000  42.000000  42
b   1.000000  42.000000  42
c  42.000000   2.000000  42
d  42.000000   3.000000  42
e  42.000000   4.000000  42
f  42.000000  42.000000   5
g  42.000000  42.000000   6
0   0.011167   1.037082 NaN
1  -1.159355  -2.087657 NaN